spring:
  liquibase:
    change-log: classpath:/db/changelog/user-info.xml
    enabled: true
    drop-first: false

  datasource:
    url: jdbc:mysql://localhost:3306/registered_users
    username: root
    password: rinathajiyev2002
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: haciyev.rinat.2002@gmail.com
    password: qzyqoysguydqvahg # If you enabled two step verification in your gmail account, you need to require an application-specific password for this
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

twilio:
  account_sid: ACd09b9712f605191f972d48f04dbf7026
  auth_token: e6e0c2d780c6ed08c749de72911b2229
  trial_number: +16205298869



